@baseUrl = http://localhost:3000/api

### @name getTodos
GET {{baseUrl}}/todos

###

# @name addNewTodo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "new",
  "id": 11,
  "isComplete": false
}

###
# @name updatePost
PUT  http://localhost:3000/api/todos/1
Content-Type: application/json

{
  "title": "edit",
  "status": "active"
}


###
# @name removeTodo
DELETE   http://localhost:3000/api/todos/11
Content-Type: application/json
